{% set name = "mongita" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mongita-{{ version }}.tar.gz
  sha256: 27487d1deb40d83e4ecb107c3d9d732d369a83cc5f10599ba86fc024e2ce9cda

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pymongo >=3.0,<5.0
    - python >=3.7
    - sortedcontainers >=2.3,<3.0

test:
  imports:
    - benchmark_tests
    - mongita
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scottrogowski/mongita
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Mongita is to MongoDB as SQLite is to SQL
  description: |
    Mongita is a lightweight embedded document database that implements a
    commonly-used subset of the MongoDB/PyMongo interface. Mongita differs
    from MongoDB in that instead of being a server, Mongita is a self-
    contained Python library. Mongita can be configured to store its
    documents either on disk or in memory.
  doc_url: https://github.com/scottrogowski/mongita
  dev_url: https://github.com/scottrogowski/mongita

extra:
  recipe-maintainers:
    - jan-janssen
